repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.4
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.0
  hooks:
  -   id: mypy
      args: [--ignore-missing-imports, --strict]
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli
